### PR TITLE
Added support for Laravel 10 (+ update testing matrix)

### PR DESCRIPTION
**Pull request by lptn**
## Summary
Add support with updated testing matrix, also run tests on PHP 8.2.
A number of combinations in matrix is pretty high, I think with the release of Laravel 10 it's a time to drop Laravel 8 support (and thus, PHP 7.3 and PHP 7.4 that are [also out of support](https://www.php.net/supported-versions.php))

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] Misc. change (internal, infrastructure, maintenance, etc.)

### Checklist
- [ ] Existing tests have been adapted and/or new tests have been added
- [x] Add a CHANGELOG.md entry
- [ ] Update the README.md
- [ ] Code style has been fixed via `composer fix-style`

______

Why this PR: we need this package to support Laravel 10 as this is a dependency of our another package where I'm a collaborator: https://github.com/psalm/psalm-plugin-laravel. Current package blocks us to improve Laravel 10 support.

### CODE REVIEW

**Review by barryvdh — APPROVED** [review]

**Comment by barryvdh** [comment]
Already merged https://github.com/barryvdh/laravel-ide-helper/pull/1406 but that doesn't have the integration tests yet.

**Comment by barryvdh** [comment]
<8.1 still needs to be excluded from the matrix.

**Comment by lptn** [comment]
@barryvdh 
Just fixed another case: [c259249](https://github.com/barryvdh/laravel-ide-helper/pull/1407/commits/c259249ad3640010a2e237281680c643737bc6f8)

**Comment by barryvdh** [comment]
Yeah all green, thanks!

**Pull request merged**
