### PR TITLE
Fix issue 784 `Arr` and `Str` no autocomplete.

### PR DESCRIPTION
**Pull request by liquid207**

### CODE REVIEW

**Comment by barryvdh** [comment]
What does this fix?

**Comment by liquid207** [comment]
Before:
Screen Shot 2019-09-17 at 10 13 30 AM
After installation:
Screen Shot 2019-09-17 at 10 06 24 AM


This PR fixes the problem described above.

**Comment by netpok** [comment]
This removes the alias too, so not better solution

**Comment by mfn** [comment]
Is this the same as https://github.com/barryvdh/laravel-ide-helper/pull/841 ?

**Pull request closed without merging**
