### PR TITLE
This is only used while developing

### PR DESCRIPTION
**Pull request by JeyKeu**

### CODE REVIEW

**Comment by barryvdh** [comment]
Yeah but people should then also realize they can't just add it to the list of providers, otherwise it will crash.

**Comment by shehi** [comment]
Yea this change is meaningless - most of us already have thought this through.

**Comment by onigoetz** [comment]
Well, you could also do the following in your `config/app.php`:
```php
if (getenv('APP_ENV') == 'local') {
    $conf['providers'][] = 'Barryvdh\LaravelIdeHelper\IdeHelperServiceProvider';
}
```

**Comment by barryvdh** [comment]
You can submit a PR to the readme if you want :)

**Pull request closed without merging**
