### PR TITLE
[WIP] Laravel 5.0 version

### PR DESCRIPTION
**Pull request by barryvdh**
Issue for keeping track of updating to L5.

### CODE REVIEW

**Comment by BardiaAfshin** [comment]
Just tried installing the ide-helper for 2.0 dev stability

Here's a copy of my composer.json
```json
{
	"name": "laravel/laravel",
	"description": "The Laravel Framework.",
	"keywords": ["framework", "laravel"],
	"license": "MIT",
	"type": "project",
	"require": {
		"laravel/framework": "~5.0",
	    "barryvdh/laravel-ide-helper": "~2.0"

	},
	"require-dev": {
		"phpunit/phpunit": "~4.0",
		"phpspec/phpspec": "~2.1"
	},
	"autoload": {
		"classmap": [
			"database"
		],
		"psr-4": {
			"App\\": "app/"
		}
	},
	"autoload-dev": {
		"classmap": [
			"tests/TestCase.php"
		]
	},
	"scripts": {
		"post-install-cmd": [
			"php artisan clear-compiled",
			"php artisan optimize"
		],
		"post-update-cmd": [
			"php artisan clear-compiled",
			"php artisan optimize"
		],
		"post-create-project-cmd": [
			"php -r \"copy('.env.example', '.env');\"",
			"php artisan key:generate"
		]
	},
	"config": {
		"preferred-install": "dist"
	},
	"minimum-stability": "dev"
}
```
and here's an output of running ./artisan aftewards

```
[32mLaravel Framework[39m version [33m5.0-dev[39m

[33mUsage:[39m
 [options] command [arguments]

[33mOptions:[39m
 [32m--help[39m (-h)           Display this help message
 [32m--quiet[39m (-q)          Do not output any message
 [32m--verbose[39m (-v|vv|vvv) Increase the verbosity of messages: 1 for normal output, 2 for more verbose output and 3 for debug
 [32m--version[39m (-V)        Display this application version
 [32m--ansi[39m                Force ANSI output
 [32m--no-ansi[39m             Disable ANSI output
 [32m--no-interaction[39m (-n) Do not ask any interactive question
 [32m--env[39m                 The environment the command should run under.

[33mAvailable commands:[39m
 [32mclear-compiled      [39m Remove the compiled class file
 [32mdown                [39m Put the application into maintenance mode
 [32menv                 [39m Display the current framework environment
 [32mhelp                [39m Displays help for a command
 [32minspire             [39m Display an inspiring quote
 [32mlist                [39m Lists commands
 [32mmigrate             [39m Run the database migrations
 [32moptimize            [39m Optimize the framework for better performance
 [32mserve               [39m Serve the application on the PHP development server
 [32mtinker              [39m Interact with your application
 [32mup                  [39m Bring the application out of maintenance mode
[33mapp[39m
 [32mapp:name            [39m Set the application namespace
[33mauth[39m
 [32mauth:clear-resets   [39m Flush expired password reset tokens
[33mcache[39m
 [32mcache:clear         [39m Flush the application cache
 [32mcache:table         [39m Create a migration for the cache database table
[33mconfig[39m
 [32mconfig:cache        [39m Create a cache file for faster configuration loading
 [32mconfig:clear        [39m Remove the configuration cache file
[33mdb[39m
 [32mdb:seed             [39m Seed the database with records
[33mevent[39m
 [32mevent:generate      [39m Generate the missing events and handlers based on registration
[33mhandler[39m
 [32mhandler:command     [39m Create a new command handler class
 [32mhandler:event       [39m Create a new event handler class
[33mkey[39m
 [32mkey:generate        [39m Set the application key
[33mmake[39m
 [32mmake:command        [39m Create a new command class
 [32mmake:console        [39m Create a new Artisan command
 [32mmake:controller     [39m Create a new resource controller class
 [32mmake:event          [39m Create a new event class
 [32mmake:middleware     [39m Create a new middleware class
 [32mmake:migration      [39m Create a new migration file
 [32mmake:model          [39m Create a new Eloquent model class
 [32mmake:provider       [39m Create a new service provider class
 [32mmake:request        [39m Create a new form request class
[33mmigrate[39m
 [32mmigrate:install     [39m Create the migration repository
 [32mmigrate:refresh     [39m Reset and re-run all migrations
 [32mmigrate:reset       [39m Rollback all database migrations
 [32mmigrate:rollback    [39m Rollback the last database migration
 [32mmigrate:status      [39m Show a list of migrations up/down
[33mqueue[39m
 [32mqueue:failed        [39m List all of the failed queue jobs
 [32mqueue:failed-table  [39m Create a migration for the failed queue jobs database table
 [32mqueue:flush         [39m Flush all of the failed queue jobs
 [32mqueue:forget        [39m Delete a failed queue job
 [32mqueue:listen        [39m Listen to a given queue
 [32mqueue:restart       [39m Restart queue worker daemons after their current job
 [32mqueue:retry         [39m Retry a failed queue job
 [32mqueue:subscribe     [39m Subscribe a URL to an Iron.io push queue
 [32mqueue:table         [39m Create a migration for the queue jobs database table
 [32mqueue:work          [39m Process the next job on a queue
[33mroute[39m
 [32mroute:cache         [39m Create a route cache file for faster route registration
 [32mroute:clear         [39m Remove the route cache file
 [32mroute:list          [39m List all registered routes
[33mschedule[39m
 [32mschedule:run        [39m Run the scheduled commands
[33msession[39m
 [32msession:table       [39m Create a migration for the session database table
[33mvendor[39m
 [32mvendor:publish      [39m Publish any publishable assets from vendor packages

```

**Comment by stevenmyhre** [comment]
When I run the generate command in L5, I'm left with an _ide_helper.php file which only has methods built for the items in the `extras` array.  Not so helpful... any idea how to get it to generate my methods for my own facades too?

**Comment by BardiaAfshin** [comment]
I'm not sure if the latest merge to master is supposed to show up in the ~2.0 version, but when I run the composer update and then run

```bash
./artisan
```
I don't see the ide-helper in the list of commands.

Here's my complete composer.json for clarity

```json
{
	"name": "laravel/laravel",
	"description": "The Laravel Framework.",
	"keywords": ["framework", "laravel"],
	"license": "MIT",
	"type": "project",
	"require": {
	  "laravel/framework": "5.0.*@dev",
	  "videlalvaro/php-amqplib": "2.2.*",
		"barryvdh/laravel-ide-helper": "~2.0"
	},
	"require-dev": {
		"phpunit/phpunit": "~4.0",
		"phpspec/phpspec": "~2.1"
	},
	"autoload": {
		"classmap": [
			"database"
		],
		"psr-4": {
			"App\\": "app/"
		}
	},
	"autoload-dev": {
		"classmap": [
			"tests/TestCase.php"
		]
	},
	"scripts": {
		"post-install-cmd": [
			"php artisan clear-compiled",
			"php artisan optimize"
		],
		"post-update-cmd": [
			"php artisan clear-compiled",
			"php artisan optimize"
		],
		"post-create-project-cmd": [
			"php -r \"copy('.env.example', '.env');\"",
			"php artisan key:generate"
		]
	},
	"config": {
		"preferred-install": "dist"
	}
}
```

**Comment by barryvdh** [comment]
Did you add the service provider?

**Comment by iBotPeaches** [comment]
I added the service provider `'Barryvdh\LaravelIdeHelper\IdeHelperServiceProvider',` to the `providers` array and I also do not have anything `ide-helper` as a command.

I also tested `~2.0@dev`

**Comment by barryvdh** [comment]
Can you clear the storage folder or something? are you in production or local environment?

**Comment by iBotPeaches** [comment]
That did the trick :)

I was local, clearing storage folder fixed it.

**Pull request closed without merging**
