### PR TITLE
Test `auth` is binded before detect Auth driver

### PR DESCRIPTION
**Pull request by zhwei**
some project may not need Auth service provider

#649

### CODE REVIEW

**Comment by mfn** [comment]
How do you produce such a scenario when it's always bound in `\Illuminate\Foundation\Application::registerCoreContainerAliases`? Is it a project using separate components?

Just curious…

**Comment by zhwei** [comment]
@mfn Aliases created in `registerCoreContainerAliases` is  `\Illuminate\Auth\AuthManager::class` 
 link to `auth`,  `auth` is bind in  `\Illuminate\Auth\AuthServiceProvider::registerAuthenticator`

so if unregister AuthServiceProvider,  `bound('auth')` will be false.

**Comment by zhwei** [comment]
anyone can review this PR?

**Comment by mfn** [comment]
Thanks for the details, much appreciated 🙇

**Pull request merged**
