### PR TITLE
Ability to use patterns for model_locations

### PR DESCRIPTION
**Pull request by 4n70w4**
Example: app/Services/*/Models

### CODE REVIEW

**Comment by mfn** [comment]
Thanks, can you describe your use-case a bit?

**Comment by 4n70w4** [comment]
@mfn case: process models from all services/modules by one rule.

config/ide-helper.php
```
    'model_locations' => array(
        'app/Services/*/Models',
    ),
`

```bash
tree app/Services/ -d -L 1
```

```
app/Services/
|-- AAAService
|-- ApplicationServices
|-- BBBService
|-- CCCService
|-- ConfirmationService
|-- DDDService
|-- EEEService
|-- FFFService
|-- GeoReferenceService
|-- GlobalPatchService
|-- HelperService
|-- KeycloakServices
|-- OOOService
|-- PPPService
|-- QQQService
|-- RRRService
|-- ShortlinkService
`-- TradingPlatformService

18 directories
```

**Comment by mfn** [comment]
> are not supported

#fail 🤦‍♂️

Of course I meant "are **now** supported" 😄

**Comment by barryvdh** [comment]
Thanks!

**Comment by 4n70w4** [comment]
@mfn If you tell me, then I don’t understand what it is and where it is.

**Comment by mfn** [comment]
@4n70w4 nevermind, already made a PR myself => https://github.com/barryvdh/laravel-ide-helper/pull/925

**Pull request merged**
