### PR TITLE
Remove L7 factory builder support

### PR DESCRIPTION
**Pull request by netpok**
## Summary
This PR removes factory builder support since the package does not support L7 or lower anymore.

## Type of change

- [x] This change requires a documentation update
- [x] Misc. change (internal, infrastructure, maintenance, etc.)

### Checklist
- [x] Existing tests have been adapted and/or new tests have been added
- [ ] Add a CHANGELOG.md entry
- [x] Update the README.md
- [x] Code style has been fixed via `composer fix-style`

### CODE REVIEW

**Review by mfn — COMMENTED** [review]
Oh, I didn't realize. I also never used this, so …

Basically LGTM but better have @barryvdh check this 😬

**Comment by mfn** [comment]
PS: best reviewed with https://github.com/barryvdh/laravel-ide-helper/pull/1182/files?w=1

**Comment by barryvdh** [comment]
Was the factory builder removed?

**Comment by netpok** [comment]
Yes it was, but actually there is a support package for it, closing this in favor of #1187

**Pull request closed without merging**
