### PR TITLE
Fix camelCase duplicated properties generator.

### LINKED ISSUE #880: Camel case properties is not working as expected
Hi, currently there is a problem in the implementation of camel cased properties implemented in #326 (the bug is present since 2016). 

If you use the command `php artisan ide-helper:models`, you will generate the docblocks. 
If you don't change anything and run the command again, some properties will duplicate (for example, if you have:
` * @property-read int|null $modelsCount`
Every time you run the command it will append to the docblock the same property.

This happens because the method checks if the property is present BEFORE the property is camelCased, therefore, the `$name` is never in the `$properties` array, appending the property each time the command is run

I will create a pull request fixing this ;)

#881 Fixes the problem

### PR DESCRIPTION
**Pull request by bop10**
Fixes #880

### CODE REVIEW

**Comment by mfn** [comment]
@bop10 tests are failing, see the red ones at https://travis-ci.org/barryvdh/laravel-ide-helper/builds/639458535?utm_source=github_status&utm_medium=notification

**Comment by bop10** [comment]
@mfn I reverted my changes in local, runned phpunit, and the same tests fail (it seems that it's not related to my changes), do you need help in this one?

**Comment by mfn** [comment]
@bop10 bummer; thanks => https://github.com/barryvdh/laravel-ide-helper/pull/882 will fix that!

**Comment by mfn** [comment]
Btw, your fix is correct AFAICS, thanks 👍 

Small wish: could you add a test which, in general, works with `model_camel_case_properties` and shows this off?

That would be awesome (copypasta of existing one should solve 80% of the work)

**Comment by bop10** [comment]
Ok! I'll try and update this pull request

**Comment by bop10** [comment]
Tests added and passed  👍

**Comment by mfn** [comment]
I fixed some other tests which failed, can you rebase please? I hope the checks are green afterwards. Thank you!

**Comment by bop10** [comment]
Done 👍

**Comment by mfn** [comment]
@barryvdh IMHO we're good here!

**Comment by davidGM-00** [comment]
Hey, is there an estimated time to merge this one?  Thanks!

**Comment by mfn** [comment]
Try requesting a review from @barryvdh if you can

**Comment by bop10** [comment]
@barryvdh Can you take a look at this one? Thanks!

**Pull request merged**
