### PR TITLE
Don't use force aliases loading

### PR DESCRIPTION
**Pull request by dkulyk**
Another autoloader throw exception if aliases not exists.

### CODE REVIEW

**Comment by barryvdh** [comment]
Which one?

**Comment by dkulyk** [comment]
Yii1 autoloader throws error if alias not set in laravel.

**Comment by barryvdh** [comment]
Thanks

**Comment by inkvizytor** [comment]
After this change function class_exists('Auth', false) always returns false because 'Auth' class is not loaded before line 120. In result ide-helper does not generate autocomplete for Auth's magic methods.

**Comment by barryvdh** [comment]
Reverted

**Pull request merged**
