### PR TITLE
Make hasOne and morphOne nullable.

### PR DESCRIPTION
**Pull request by leo108**

### CODE REVIEW

**Comment by mr-feek** [comment]
Thank you 🙌 `HasOne` should be nullable indeed

**Comment by mfn** [comment]
Ran into this today in fact 😅 @leo108 are you still interesting in completing this from my feedback?

**Comment by leo108** [comment]
@mfn sorry for the delay, I'll fix this ASAP

**Comment by leo108** [comment]
@mfn Fixed, please check.

**Comment by leo108** [comment]
@barryvdh Can you merge this?

**Pull request merged**
