### PR TITLE
Form request helpers

### PR DESCRIPTION
**Pull request by shomisha**
This pull request exposes a command for generating phpDocs for Laravel's FormRequests. 
The command supports generating docBlocks both inline, in the same files where class declarations are, and inline. 
It also supports parsing FormRequests from custom locations, not just the default one, as well as skipping specified form requests when generating phpDocs.

### CODE REVIEW

**Comment by lexdewilligen** [comment]
@barryvdh @shomisha Any updates on this? I like the feature

**Comment by shomisha** [comment]
@lexdewilligen Not sure, @barryvdh is not responding. Not sure if the repo is still maintained, there are a lot of open PR's

**Comment by barryvdh** [comment]
Sorry I don't really use form requests. Why do they need this generation?

**Comment by lexdewilligen** [comment]
Haha for just that purpose. I like to use form requests as much as possible. Would be nice to auto generate docblocks for it.

**Comment by shomisha** [comment]
@barryvdh You can have autocomplete for the values you can get off of requests, and all of that based on validation rules. This functionality teaches the IDE what's available in a request inside a specific controller method that has a form request type hinted

**Comment by misa-neopix** [comment]
@barryvdh I fixed the code smells. If you want, approve the PR, or deny it, can you just resolve it, please?

**Comment by kyori19** [comment]
Any updates on this PR?

**Pull request closed without merging**
