### PR TITLE
Consider foreign key constraints with isRelationNullable

### PR DESCRIPTION
**Pull request by atushi-koga**
## Summary
When we run ide-helper:models on a class that defines a method that uses belongsTo, if the foreign key used for the relation is not null, a doc comment will be generated with the property returned as the relation class.

```php
<?php

use Illuminate\Database\Eloquent\Model;

/**
 * @property-read App\User $user  <- returned type is relation class
 * @mixin \Eloquent
 */
class Phone extends Model
{
    public function user()
    {
        return $this->belongsTo('App\User');
    }
}
```

However, there are times when we want to get the relation class **without using the foreign key constraint**, so we check for the existence of the relation class.
Therefore, static analysis with the current doc comments will fail, with the null check always resulting in false.

```php
$phone = Phone::firstOrFail();
if (is_null($phone->user)) {  // static analysis says 「It's dead code because it's always false」
    throw new RuntimeException('User Not Found');
}
$user = $phone->user
```

This problem can be solved by checking for the presence of foreign key constraints.
Is it possible to import this change?

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] Misc. change (internal, infrastructure, maintenance, etc.)

### Checklist
- [x] Existing tests have been adapted and/or new tests have been added
- [ ] Add a CHANGELOG.md entry
- [ ] Update the README.md
- [x] Code style has been fixed via `composer fix-style`

### CODE REVIEW

**Review by Messhias — APPROVED** [review]

**Comment by barryvdh** [comment]
So this would make $user nullable? Can you add a testcase for this?

**Review by barryvdh — CHANGES_REQUESTED** [review]
Please add tests to validate this behavior.

**Comment by Messhias** [comment]
> Please add tests to validate this behavior.

Hi @barryvdh, I'll try to give a test case to validate this behavior, I don't know if I can do it today, but I'll try at least on weekend to do that. 

I didn't open the PR but I guess I can help handle this.

Thank you,

**Comment by atushi-koga** [comment]
@Messhias 
Oh, I'm glad for your help as I'm still new to this.

**Comment by Messhias** [comment]
> @Messhias
> Oh, I'm glad for your help as I'm still new to this.

You wanna try by yourself to do the tests? If you are not able to do it I can do it, but probably it'll be only on weekends if I arrange some time to do it.

**Comment by atushi-koga** [comment]
@Messhias 
Thank you for giving me a chance. I'll try!

**Comment by atushi-koga** [comment]
Added a test.

**Review by Messhias — APPROVED** [review]
It seems fine on PHP 8.0.9.

**Comment by Messhias** [comment]
@barryvdh it's seems fine now :)

**Review by barryvdh — APPROVED** [review]

**Pull request merged**
