### PR TITLE
Add support for facades which resolve to classes that are sometimes not bound in the container

### PR DESCRIPTION
**Pull request by stancl**
Context: https://github.com/stancl/tenancy/issues/353#issuecomment-612906249

Didn't run any tests so hopefully this doesn't break anything.

### CODE REVIEW

**Comment by stancl** [comment]
@mfn 

The test would be that I didn't break anything & this now works:

```php
class Foo {}

class FooFacade extends Facade
{
    public function getFacadeAccessor()
    {
        return Foo::class;
    }
}
```

An alias should be generated even if no specific instance of `Foo` is currently bound in the container.

**Comment by mfn** [comment]
Can you add this as a test? So no one else breaks "your" change :)

**Comment by stancl** [comment]
Seems like my solution doesn't fix the bug: https://github.com/stancl/tenancy/issues/353#issuecomment-614434837

Will look deeper into it once I get the chance.

**Comment by barryvdh** [comment]
So is this required or not?

**Comment by stancl** [comment]
This will require some more work probably. Will open a new PR if I get to it.

**Pull request closed without merging**
