### PR TITLE
__toString function has been DEPRECATED

### PR DESCRIPTION
**Pull request by cxlblm**
__toString function has been DEPRECATED as of PHP 7.4.0

### CODE REVIEW

**Comment by barryvdh** [comment]
Can you fix the merge conflict?

**Comment by cxlblm** [comment]
> Can you fix the merge conflict?

Ok, I fixed!

**Comment by sebastiaanluca** [comment]
@barryvdh Can you tag a release for this? Thanks!

**Comment by barryvdh** [comment]
Done

**Pull request merged**
