### PR TITLE
Add ignored_models as config option

### PR DESCRIPTION
**Pull request by pataar**
This makes it easier for the IDE to refactor those classes when needed. And it makes it easier to add multiple models with long namespaces.

### CODE REVIEW

**Comment by pataar** [comment]
Hey @mfn, any idea when you can check this one? Thanks!

**Comment by mfn** [comment]
@pataar looks good to me!

Personally would be great to have a test. Right now that area if "ignore classes" has none at all. Could be a good opportunity to start them with this…

**Comment by pataar** [comment]
@mfn I added a test :)

**Comment by mfn** [comment]
@pataar Nice :-)

From my side very much appreciated!

@barryvdh LGTM!

**Comment by pataar** [comment]
Thanks for checking and merging!

**Pull request merged**
