### PR TITLE
Remove register provider

### PR DESCRIPTION
**Pull request by ahmed-aliraqi**
You do not need to register service provider on non-production enviroment because it already registered using laravel package discovery

### CODE REVIEW

**Comment by mfn** [comment]
Actually, I would say let's go the other way and remove the auto-discovery.

Because the auto discover means, it's always loaded. But you don't (shouldn't) need to load this in production.

As such, rather the readme should say but we should remove it from composer.json…

**Comment by barryvdh** [comment]
With the --dev flag and auto Discovery, it's never loaded in production. So this looks good to me.

**Comment by barryvdh** [comment]
Only it has conflicts so cannot merge this.

**Comment by mfn** [comment]
> With the --dev flag and auto Discovery, it's never loaded in production. So this looks good to me.

Yeah, correct. But I still think it doesn't harm to keep it in the readme for those who don't / can't / won't use auto-discovery as additional hint what to watch out for.

**Pull request closed without merging**
