### PR TITLE
morphOne and morphTo fixes

### PR DESCRIPTION
**Pull request by boxfrommars**
Adds property method for `morphOne` relation 
and fixes relation model for `morphTo` relation (`morphTo` first argument is not a relation model)

### CODE REVIEW

**Comment by barryvdh** [comment]
Should morphTo return static?

**Comment by boxfrommars** [comment]
`MorphTo::getResult` returns `\Illuminate\Database\Eloquent\Builder::first` i.e. 
`\Illuminate\Database\Eloquent\Model|static|null`

**Comment by boxfrommars** [comment]
that is the same thing as belongsto, except that we do not know the specific class of relation

**Comment by boxfrommars** [comment]
@barryvdh should i replace `\Illuminate\Database\Eloquent\Model` with `\Illuminate\Database\Eloquent\Model|static|null` for MorphTo?

**Comment by barryvdh** [comment]
Sorry, had merge conflicts. Add it in above commit, thanks!

**Pull request closed without merging**
