### PR TITLE
Support both customized namespace factories as well as default resolvable ones

### PR DESCRIPTION
**Pull request by wimski**
## Summary
In response to a discussion I started: https://github.com/barryvdh/laravel-ide-helper/pull/1196#issuecomment-812173816.

## Type of change
- [x] Bug fix (non-breaking change which fixes an issue)

### Checklist
- [x] Existing tests have been adapted and/or new tests have been added
- [ ] Add a CHANGELOG.md entry
- [x] Code style has been fixed via `composer fix-style`

### CODE REVIEW

**Comment by ahmed-aliraqi** [comment]
@wimski Really I think using `Factory::resolveFactoryName($modelName)` is better, I agree with you :+1:

**Review by mfn — APPROVED** [review]
Looks legit to me and I'm onboard it it works now better for everyone!

@wimski could you please add a changelog? I imagine we might release this ASAP

@barryvdh 👍

**Review by barryvdh — APPROVED** [review]

**Comment by wimski** [comment]
> wimski could you please add a changelog? I imagine we might release this ASAP

Seems like it's already merged 🤷‍♂️

**Comment by mfn** [comment]
no problem :) => https://github.com/barryvdh/laravel-ide-helper/pull/1203

**Pull request merged**
