### PR TITLE
Optionally write missing Laravel Model DocBlock

### PR DESCRIPTION
**Pull request by iPaat**
Hi,

This will solve the problem from #699, #697 and #695.

This patch will not completely disable the addition of mixins like https://github.com/barryvdh/laravel-ide-helper/commit/7db1843473e1562d8e0490b51db847d3a1415140, but make them optional.

It would be really wonderful to continue to have this option as it greatly simplifies the work. But since not everyone wants `/vendor` files to be changed, this behavior is now optional.

The changes to add the mixins are the same as in #624 .

Best,
Patrick

---

Fixes: #715 #716

### CODE REVIEW

**Comment by newlinkcapital** [comment]
How can this option be activated?
Cheers.

**Comment by iPaat** [comment]
Hi,
in your config file set the `'write_eloquent_model_mixins'` option to `true` or use the `-W` option: `php artisan ide-helper:models -W`.

Best,
Patrick

**Comment by bleuscyther** [comment]
@iPaat thx. I was using Lumen. I Downloaded the new config file.

has you mentioned 

```php
return array([
...
'write_eloquent_model_mixins' => true,
...
];
```
fixed it for me.

**Comment by diegormb06** [comment]
> Hi,
> in your config file set the `'write_eloquent_model_mixins'` option to `true`.
> 
> Best,
> Patrick

I am study laravel, and it has many config files. Where specificaly i should put this rule?

**Comment by mfn** [comment]
This package has it's own in `config/ide-helper.php` *iff* you published it; see the README for details on that

**Pull request merged**
