### PR TITLE
Add an eloquent command

### PR DESCRIPTION
**Pull request by Artistan**
for adding the `@mixin \Eloquent` to the Illuminate\Database\Eloquent\Model

### CODE REVIEW

**Comment by Artistan** [comment]
This may be called by itself, or possibly when the ide-helper is run?

**Comment by barryvdh** [comment]
Why does it need to be a separate command?

**Comment by Artistan** [comment]
No need really, I just did not want to presume where you thought it should be added.  Is it part of the ide-helper, or the model writer, or a seperate command. As it's own command it could be run by itself for but I guess it is useless without the writing of the \Eloquent mixin.

**Comment by Artistan** [comment]
I will add it to the Generate class, since that creates the \Eloquent helper.

**Comment by Artistan** [comment]
@barryvdh , I updated the Generator so it will add the mixin to the Eloquent\Model after the helper is created. (since it is irrelevant without the helper) 

1. Eloquent class as a helper, similar to Generator (separation of logic)
2. Add helper to write mixin to Model class after creating helper
3. keep command to allow running mixin writer in case of updating framework

**Comment by Artistan** [comment]
mixin written to file...
image

mixin already exists...
image

**Comment by Artistan** [comment]
bump.

**Comment by artem328** [comment]
When this estimated to release?

**Comment by KerryJones** [comment]
+1

**Comment by GTCrais** [comment]
+1

**Comment by ErSulba** [comment]
this resolves so many headaches.... i'm waiting for this, since laravel and phpstorm last update makes me to manually config all over again every project i have

**Comment by ivansammartino** [comment]
Still I get PHPStorm warning when using code like `User::truncate();` in `DatabaseSeeder.php` (everything else seems to work fine)

**Comment by kmark** [comment]
This only works for me if the added tag is the before the others already in my `Model.php`. Since, at least for me, it is not, this doesn't work (due to only appending the tag).

**Pull request merged**
