### PR TITLE
chore: add missing changelog entries

### PR DESCRIPTION
**Pull request by mfn**
## Summary
- Added https://github.com/barryvdh/laravel-ide-helper/pull/1005
- Added https://github.com/barryvdh/laravel-ide-helper/pull/1163

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] Misc. change (internal, infrastructure, maintenance, etc.)

### Checklist
- [ ] Existing tests have been adapted and/or new tests have been added
- [x] Add a CHANGELOG.md entry
- [ ] Update the README.md
- [ ] Code style has been fixed via `composer fix-style`

### CODE REVIEW

**Comment by mfn** [comment]
Also added https://github.com/barryvdh/laravel-ide-helper/pull/1163

**Review by barryvdh — APPROVED** [review]

**Comment by mfn** [comment]
@barryvdh would you mind if a tag a new release based on master, 2.9.1?

**Comment by barryvdh** [comment]
yes done.

**Comment by mfn** [comment]
@barryvdh thanks, I updated the description https://github.com/barryvdh/laravel-ide-helper/releases/tag/v2.9.1

**Comment by netpok** [comment]
@mfn sorry to bother you but could you fix my name in the changelog next time you edit it?

**Comment by barryvdh** [comment]
Fixed

**Comment by mfn** [comment]
Thanks @barryvdh and sorry @netpok 😬

I should really bug people to just add it themselves heh

**Pull request merged**
