### PR TITLE
Eloquent mixin

### PR DESCRIPTION
**Pull request by ababkov**
Option to add ```@mixin \Eloquent``` to model doc block if the model extends from Illuminate\Database\Eloquent\Model.

### CODE REVIEW

**Comment by ababkov** [comment]
@barryvdh Any thoughts on this one?

Cheers.

**Comment by barryvdh** [comment]
Hmm, I'm not 100% sure about this. It will probably solve a few cases, but not all, right? Why not just extend the facade instead?

**Comment by ababkov** [comment]
Mostly on the grounds that the current documentation always extends the Model (http://laravel.com/docs/5.0/eloquent) which leads me to believe that most people will extend the base class rather than the facade. 

Additionally, if you're extending a third party class that extends Model rather than the facade you don't have much choice.

I've been using the mixin for a while with a fair amount of success - my only complaint is that the type hinting on some of the builder methods is a bit annoying as it never type hints static return types for methods like Eloquent::findOrFail() and firstOrFail(). That being said, at least they hint now..

Without putting in special exceptions this is maybe the best we can do.

Anyway, curious to hear your thoughts on potential issues - you've been doing this laravel thing for a while longer than me :)

**Comment by barryvdh** [comment]
It should extend both the Eloquent Builder and the Query Builder, right?

The problem I had with it, was that it flagged some errors/warning, because it was behaving as if it was extending the class. Can't exactly remember what.

But if it is an option I guess it wouldn't hurt.

**Comment by ababkov** [comment]
Not sure on extending the QueryBuilder - the methods in there start to get pretty low level - happy to take your thoughts on this.

On a slightly unrelated note and out of curiosity - do you have any idea why some of the query builder methods in Laravel hint Collection|static[] or Model|static and others omit static.

e.g. findOrFail
@return \Illuminate\Database\Eloquent\Model|\Illuminate\Database\Eloquent\Collection

Surely this should be:
@return \Illuminate\Database\Eloquent\Model|\Illuminate\Database\Eloquent\Collection|static|static[]

If not I might go through at some point and submit a pull request.

**Comment by Doncode** [comment]
Hi. What about findOrFail
Autocomplete does not work for findOrFail (laravel 5)

**Comment by Lavoaster** [comment]
What's the status on this? It'd be helpful for me because I have a preference for staying with the default and just extending `Model` instead of eloquent.
I would however suggest that the config option is disabled by default, so it won't affect anyone that this won't be useful for.

**Comment by shehi** [comment]
+1 for this.

**Comment by cablegunmaster** [comment]
+1 is there a update for this one? :)

**Comment by ababkov** [comment]
@barryvdh - any chance this will be merged in at some point?

**Comment by m3esma** [comment]
+1

**Comment by m3esma** [comment]
+1 — this is a good thing.

**Comment by CaporalDead** [comment]
:+1: please :)

**Comment by barryvdh** [comment]
If we're going to use mixin, why not use the actual classes, instead of the facade?

**Comment by CaporalDead** [comment]
Not sure to get what you said. Can you explain it to me plz ?

**Comment by ababkov** [comment]
Yeah fair enough - I'll sort out next week

**Comment by barryvdh** [comment]
Fixed with https://github.com/barryvdh/laravel-ide-helper/commit/c213be3d3ca95a788aa4f1d9ddf72d4f31700594

**Pull request closed without merging**
