### PR TITLE
Update ModelsCommand.php

### PR DESCRIPTION
**Pull request by MrCue**
Work with tables in different databases

### CODE REVIEW

**Comment by EselDompteur** [comment]
+1 for that

MrCue <notifications@github.com> schrieb am Mi., 13. Mai 2015 um 17:49 Uhr:

**Comment by barryvdh** [comment]
When is this needed?

**Comment by EselDompteur** [comment]
if you are using different databases in the same project

Barry vd. Heuvel <notifications@github.com> schrieb am Do., 14. Mai 2015 um
10:09 Uhr:

**Comment by MrCue** [comment]
When you generate the model documentation, if your table name references a different database (somedatabase.table) then the documentation doesn't contain any fields from the table.

This change allows for tables from more than one database to have documentation generated.

**Comment by barryvdh** [comment]
Okay so the same db connection, but different table.

**Pull request merged**
