### PR TITLE
Fix generate error when macroable class has a "fake" method

### PR DESCRIPTION
**Pull request by domkrm**
This should fix the issue https://github.com/barryvdh/laravel-ide-helper/issues/1065

### CODE REVIEW

**Review by mfn — APPROVED** [review]
Looks legit to me 👍 

@domkrm can you add a changelog entry under "Fixed"? 🙏

**Comment by domkrm** [comment]
I have added the changelog entry.

**Review by mfn — APPROVED** [review]
@domkrm thanks, also for the quick fix 🙇 

@barryvdh IMHO good to merge!

**Comment by lloricode** [comment]
Hi, are we able to use this with release tag?

**Comment by mfn** [comment]
Unfortunately not yet, the last release was a while ago => https://github.com/barryvdh/laravel-ide-helper/releases/tag/v2.8.1

You can try if using [`2.8-dev`](https://github.com/barryvdh/laravel-ide-helper/blob/0168e7256bfec301864bd1c75b0cc1804c3b874e/composer.json#L48) works for you in the meantime

**Pull request merged**
