### PR TITLE
Fix unsetMethod in ModelsCommand

### PR DESCRIPTION
**Pull request by leo108**
## Summary

The key of `ModelsCommand::$methods` is case sensitive, so we should not convert the `$name` to lowercase when unset.

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

### Checklist
- [x] Existing tests have been adapted and/or new tests have been added
- [x] Add a CHANGELOG.md entry
- [x] Update the README.md
- [x] Code style has been fixed via `composer fix-style`

### CODE REVIEW

**Comment by leo108** [comment]
@barryvdh any chance to check this PR? thanks.

**Comment by barryvdh** [comment]
Maybe we should lowercase the check instead also?

**Comment by leo108** [comment]
@barryvdh You're right since methods are case-insensitive in PHP.

Please check the updated code.

**Comment by leo108** [comment]
@barryvdh Please check when you have time, thanks.

**Comment by leo108** [comment]
@barryvdh bump

**Comment by leo108** [comment]
@barryvdh Sorry to bother you again, but I'm really hope this PR can be merged, please let me know what your concern, thanks!

**Review by barryvdh — APPROVED** [review]

**Comment by barryvdh** [comment]
Hmm not really sure why this is failing

**Comment by barryvdh** [comment]
All good! Thanks for your patience

**Comment by leo108** [comment]
Thanks! it would be nice if you could release a new version.

**Pull request merged**
