### PR TITLE
Add extend \Eloquent for ide-helper:models command

### PR DESCRIPTION
**Pull request by matiaspub**
It's help author to close many issues! )
Like: #269, #259, #248, #209, #191, #74, 
and https://github.com/laravel/framework/issues/7558 )))
etc. maybe

### CODE REVIEW

**Comment by barryvdh** [comment]
As I said before, shouldn't we `mixin`  the actual classes?

**Comment by matiaspub** [comment]
Sorry, I didn't find it.
But Why?

**Comment by barryvdh** [comment]
Now we're linking the methods to the ide_helper file. It would be nicer if PHPstorm would actually click directly to the correct class.

**Comment by barryvdh** [comment]
Which are `Illuminate\Database\Eloquent\Builder`  and `Illuminate\Database\Query\Builder`

**Comment by matiaspub** [comment]
It would be nicer... Right!
But it could be a temporary solution.
Or we will wait until PhpStorm begins to understand @mixin static ?

**Comment by Lambik** [comment]
When I add the `mixin` to my model tag, phpstorm understands `::where()`, but subsequently complains that extra chained `->where()` and `->take()` and whatnot should be static too (`::where`, `::take`). Too bad that this is so hard to solve :(

**Comment by barryvdh** [comment]
I tested this. You are correct about PHPstorm not understanding the statics. Merged this. Thanks!

**Pull request merged**
