### PR TITLE
🐛 fixes ide-helper:generate array_merge error

### PR DESCRIPTION
**Pull request by acidjazz**
addresses issue #832

### CODE REVIEW

**Comment by netpok** [comment]
I would not expect a helper library to change the application state. In my opinion if someone decides to cache the config he/she should be the one who clears those cached values.

**Comment by mfn** [comment]
Ack, also 👎 on this PR

**Comment by acidjazz** [comment]
@netpok @mfn yall think maybe instead a check on the array itself before the `array_merge()` happens?

**Comment by mfn** [comment]
@acidjazz never encountered the error mentioned in the issue, but I see no harm if getting a config value to have a default of empty array in case it's not found (if that is what this is about?)

**Comment by mazeripper** [comment]
👎 on this also—A library should change the setup of your app, but I did encounter the same issue. Maybe there should be a question of the README highlighting that cached values should be cleared?

**Comment by mfn** [comment]
The readme was recently updated and now contains this in the [installation section](https://github.com/barryvdh/laravel-ide-helper#installation):
> Note: Avoid caching the configuration in your development environment, it may cause issues after installing this package; respectively clear the cache beforehand via php artisan cache:clear if you encounter problems when running the commands

I think the ought to be enough, caching development config is discouraged by all I ever read so far.

@barryvdh IMHO this PR should be dropped :}

**Pull request closed without merging**
