### PR TITLE
Fix ide-helper:models exception if model doesn't have factory

### LINKED ISSUE #1188: v2.9.1: `artisan ide-helper:models` stopped working after update
### Versions:
- ide-helper Version: 2.9.1
- Laravel Version: 8.33.1
- PHP Version: 7.4.15

### Description:
```
> @php artisan ide-helper:models -N
Exception: Class 'Database\Factories\PaypalNotificationFactory' not found
Could not analyze class App\Models\PaypalNotification.

Trace:
#0 /var/www/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Factories/HasFactory.php(15): Illuminate\Database\Eloquent\Factories\Factory::factoryForModel('App\\Models\\Payp...')
#1 /var/www/vendor/barryvdh/laravel-ide-helper/src/Console/ModelsCommand.php(1096): App\Models\PaypalNotification::factory()
#2 /var/www/vendor/barryvdh/laravel-ide-helper/src/Console/ModelsCommand.php(281): Barryvdh\LaravelIdeHelper\Console\ModelsCommand->getFactoryMethods(Object(App\Models\PaypalNotification))
#3 /var/www/vendor/barryvdh/laravel-ide-helper/src/Console/ModelsCommand.php(162): Barryvdh\LaravelIdeHelper\Console\ModelsCommand->generateDocs(Array, Array)
#4 /var/www/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Barryvdh\LaravelIdeHelper\Console\ModelsCommand->handle()
#5 /var/www/vendor/laravel/framework/src/Illuminate/Container/Util.php(40): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#6 /var/www/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\Container\Util::unwrapIfClosure(Object(Closure))
#7 /var/www/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Array, Object(Closure))
#8 /var/www/vendor/laravel/framework/src/Illuminate/Container/Container.php(611): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Array, Array, NULL)
#9 /var/www/vendor/laravel/framework/src/Illuminate/Console/Command.php(136): Illuminate\Container\Container->call(Array)
#10 /var/www/vendor/symfony/console/Command/Command.php(256): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#11 /var/www/vendor/laravel/framework/src/Illuminate/Console/Command.php(121): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#12 /var/www/vendor/symfony/console/Application.php(971): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#13 /var/www/vendor/symfony/console/Application.php(290): Symfony\Component\Console\Application->doRunCommand(Object(Barryvdh\LaravelIdeHelper\Console\ModelsCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#14 /var/www/vendor/symfony/console/Application.php(166): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#15 /var/www/vendor/laravel/framework/src/Illuminate/Console/Application.php(92): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#16 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(129): Illuminate\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#17 /var/www/artisan(37): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#18 {main}
```

---
Upd.
**Solution:**
Be sure to remove any `use HasFactory;` on models not having factories to avoid crashes in ide-helper

### PR DESCRIPTION
**Pull request by ahmed-aliraqi**
## Summary
fixes #1188 
- [x] Bug fix (non-breaking change which fixes an issue)

### Checklist
- [x] Existing tests have been adapted and/or new tests have been added
- [x] Add a CHANGELOG.md entry
- [x] Code style has been fixed via `composer fix-style`

### CODE REVIEW

**Review by Messhias — APPROVED** [review]

**Comment by Messhias** [comment]
I tested locally and this PR works fine, why isn't approved yet?

**Comment by barryvdh** [comment]
Sorry I can't respond to everything directly. There is an alternative PR open here: https://github.com/barryvdh/laravel-ide-helper/pull/1189

**Comment by barryvdh** [comment]
@mfn Is this good to merge? Would rather fix this issue before tagging a new version.

**Review by mfn — APPROVED** [review]
@barryvdh yes, this LGTM and I prefer it technically over https://github.com/barryvdh/laravel-ide-helper/pull/1189 , approach make sense to me!

**Comment by ahmed-aliraqi** [comment]
@mfn @barryvdh thanks for merging  if you need any help just mention me ✌️

**Comment by wimski** [comment]
@ahmed-aliraqi @mfn @barryvdh 

Shouldn't `$modelName::newFactory()` be `$modelName::factory()`? Because `newFactory` returns nothing by default, but `factory` does. And it will still use `newFactory` if it does return something.

https://github.com/laravel/framework/blob/8.x/src/Illuminate/Database/Eloquent/Factories/HasFactory.php

My models use the `HasFactory` trait and a corresponding factory exists for each model, but the annotation is not written to the model doc block.

**Comment by ahmed-aliraqi** [comment]
@wimski By default `$modelName::newFactory()` return nothing it added to give ability to customize your own factory namespace different than the laravel's default

**Comment by wimski** [comment]
@ahmed-aliraqi

Yes, I get that the `newFactory` method enables you to customize your factory namespace. What I'm saying is that the `factory` method includes that support so there's no need to use the newFactory on its own.

```php
$factory = static::newFactory() ?: Factory::factoryForModel(get_called_class());
```

Currently the IDE helper determines the factory class in two ways:
1. As a templated string `\Database\Factories\\{MODEL_NAME}Factory`.
2. Or by using the `newFactory` method to check for a custom namespace.

Both options do not work in my situation. I do use custom namespacing for both models and factories (sub division), but I don't use the `newFactory` method. The `Factory::factoryForModel(get_called_class())` seems to figure out what the corresponding factory is, probably based on the `$model` property inside the factory.

For example:
* `App\Models\Users\User`
* `Database\Factories\Users\UserFactory`

My factories work fine using this setup without having to specifically declare my custom namespace in `newFactory`. The IDE helper won't write a factory doc block for my model though, because neither of the resolver rules match my use case. Switching from `newFactory` to `factory` would, while still supporting explicit custom namespaces.

**Comment by mfn** [comment]
😱 

What shall we do 😄 

@wimski do you want to attempt another PR to continue discussion there maybe?

**Comment by ahmed-aliraqi** [comment]
@wimski @mfn @barryvdh  I suggest to move it to the config file to be able to customize your own namespace globally.

```php
// config file:
[
  ...
  'factories_namespace' => null,
  ...
]
```
```php
// ModelsCommand.php
$factory = config('ide-helper.factories_namespace') ?: "\Database\Factories\\{$modelBaseName}Factory";
```
If this solution is appropriate. wll create another PR.

**Comment by wimski** [comment]
@ahmed-aliraqi 

I don't think that will solve anything. I'm working on my own PR to support both custom namespaces and namespaces that can be resolved by default.

https://github.com/barryvdh/laravel-ide-helper/pull/1201

**Pull request merged**
