### PR TITLE
Add support for non type-hinted attribute accessors with no backed property

### PR DESCRIPTION
**Pull request by pindab0ter**
## Summary
This is a resubmission of #1338 as that got closed inadvertently.

Even though the documentation doesn't state this explicitly at the time of writing, it is possible to use the new Attribute accessor to create a calculated property where there is no backing property.

This solves #1315.

I added a check for if the Attribute accessor function has no specified type, and then add it without type.

## Type of change

- [x] New feature (non-breaking change which adds functionality)

### Checklist
- [x] Existing tests have been adapted and/or new tests have been added
- [x] Add a CHANGELOG.md entry
- [x] Code style has been fixed via `composer fix-style`

### CODE REVIEW

**Comment by pindab0ter** [comment]
Because of how the branches are now rebased on top of each other, this PR also includes #1339.

**Comment by chescos** [comment]
Hey @mfn - can we get this merged?

**Comment by ngmy** [comment]
I too am eager for this pull request to be merged.
It worked as expected in my local environment.

**Comment by pindab0ter** [comment]
I have given up on waiting for this and have stopped using this package in favour of the Laravel IDEA plugin.

**Review by barryvdh — APPROVED** [review]

**Pull request merged**
