### PR TITLE
Support variadic parameters in models command

### PR DESCRIPTION
**Pull request by shaffe-fr**
## Summary
This adds support of variadic paremeters in ModelsCommand.

## Type of change
New feature

### Checklist
- [x] Existing tests have been adapted and/or new tests have been added 
- [x] Add a CHANGELOG.md entry
- [x] Update the README.md
- [x] Code style has been fixed via `composer fix-style`

@mfn Where should I add some tests?
Thanks

### CODE REVIEW

**Review by Messhias — APPROVED** [review]

**Comment by barryvdh** [comment]
This looks good, but would it be possible to add a test to cover this?

**Comment by shaffe-fr** [comment]
Hi @barryvdh, 
I'm not sure where to put the test. Should I add it in an existing one in tests/Console/ModelsCommand? 
Thanks

**Comment by barryvdh** [comment]
Probably easiest to copy an existing test and just change a parameter to variadic.

**Comment by shaffe-fr** [comment]
I added some tests @barryvdh. Is it ok?

**Review by barryvdh — APPROVED** [review]

**Comment by mfn** [comment]
Thanks! 👍

**Pull request merged**
